---

#############################################################################
##
##  Auto-Omeka-S
##  T McIntyre for UTS EResearch 2015-16
##
#############################################################################

#############################################################################
##
##  ANSIBLE TASKS for omeka-s core
##
#############################################################################

  - name: check if omeka core is present already
    stat: path=/var/www/html/omeka-{{ omeka_version }}/index.php
    register: omekacoreexists

#   - debug: var=omekacoreexists.stat.exists

  - name: fetch omeka core
    get_url: url=https://github.com/omeka/omeka-s/archive/v{{ omeka_version }}.tar.gz dest=/tmp/omeka-s-{{ omeka_version }}.tar.gz
    register: omekacorearchivefetched
    when: not omekacoreexists.stat.exists

  - name: extract omeka core
    unarchive: src=/tmp/omeka-s-{{ omeka_version }}.tar.gz dest=/var/www/html/ creates=/var/www/html/omeka-s-{{ omeka_version }}/index.php copy=no
    register: omekacoreextracted
    when: omekacorearchivefetched|success

  - name: install omeka's db config file
    template: >
      dest=/var/www/html/omeka-s-{{ omeka_version }}/config/database.ini
      src=templates/database.ini.j2
      owner=root
      group=wheel
      mode=0644

  - name: set files dir owner as apache to allow uploads
    command: /bin/chown -R apache:apache /var/www/html/omeka-s-{{ omeka_version }}/files/

  #- name: enable display of PHP and application errors
  #  lineinfile: dest=/var/www/html/omeka-{{ omeka_version }}/.htaccess regexp='SetEnv\sAPPLICATION_ENV' line='SetEnv APPLICATION_ENV development' state=present
  #  when: omekacoreextracted|success

  - name: create us a database
    mysql_db: >
      name={{ db_name }}
      state=present

  - name: create us a db user
    mysql_user: >
      name={{ db_user }}
      password={{ db_password }}
      priv={{ db_name }}.*:ALL
      state=present

  - name: initialise omeka-s install (could take an hour or so)
    shell: ant init
    args:
      chdir: /var/www/html/omeka-s-{{ omeka_version }}/
      creates: build/composer.phar

## SOLR and plugins would be configured here if applicable
